from __future__ import annotations

from datetime import datetime, timezone

from app.models.schemas import Investigation


def generate_report(investigation: Investigation) -> str:
    dossier = investigation.dossier
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = [
        f"# Spectre OSINT Report: {investigation.target_value}",
        "",
        f"**Target:** {investigation.target_type} — {investigation.target_value}",
        f"**Investigation ID:** {investigation.id}",
        f"**Generated:** {now}",
        f"**Status:** {investigation.status}",
        f"**Turns Completed:** {len(investigation.turns) // 2}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    identity = dossier.sections.get("identity_resolution", "").strip()
    if identity:
        lines.append(identity)
        lines.append("")

    for section_key, display_name in [
        ("digital_footprint", "Digital Footprint"),
        ("timeline", "Timeline"),
        ("professional_intelligence", "Professional Intelligence"),
        ("network_map", "Network Map"),
        ("writing_style_analysis", "Writing Style Analysis"),
        ("business_intelligence", "Business Intelligence"),
        ("technical_intelligence", "Technical Intelligence"),
        ("reputation_assessment", "Reputation Assessment"),
        ("behavioral_patterns", "Behavioral Patterns"),
        ("influence_analysis", "Influence Analysis"),
        ("opportunity_analysis", "Opportunity Analysis"),
        ("verification", "Verification & Confidence Scores"),
        ("unknowns", "Unknowns"),
    ]:
        content = dossier.sections.get(section_key, "").strip()
        if content:
            lines.extend([
                f"## {display_name}",
                "",
                content,
                "",
                "---",
                "",
            ])

    if dossier.confidence_scores:
        lines.extend([
            "## Confidence Scores",
            "",
        ])
        for finding, score in dossier.confidence_scores.items():
            lines.append(f"- **{finding}:** {score}%")

    lines.extend([
        "",
        "---",
        "",
        f"*Report generated by Spectre OSINT — {now}*",
        "",
    ])

    return "\n".join(lines)
